#!/bin/bash

# 万象行者 快速APK构建指南脚本

echo "🎮 万象行者 Android APK 快速构建指南"
echo "========================================"
echo ""

# 显示当前环境状态
echo "📊 当前环境状态:"
echo "✅ Node.js: $(node --version)"
echo "✅ npm: $(npm --version)"
echo "✅ Capacitor: $(npx cap --version)"
echo "❌ Java: 未安装"
echo "❌ Android SDK: 未配置"
echo ""

echo "🚨 重要说明:"
echo "您之前尝试的命令 'Build > Build Bundle(s)/APK(s) > Build APK(s)' 是 Android Studio 的菜单操作，不是终端命令！"
echo ""

echo "🎯 推荐解决方案 (按优先级排序):"
echo ""

echo "方案1: 使用 Android Studio (最简单) 🌟"
echo "----------------------------------------"
echo "1. 下载安装 Android Studio:"
echo "   https://developer.android.com/studio"
echo ""
echo "2. 安装完成后，在终端运行:"
echo "   npx cap open android"
echo ""
echo "3. 在 Android Studio 中:"
echo "   - 等待项目加载完成"
echo "   - 点击菜单: Build → Build Bundle(s)/APK(s) → Build APK(s)"
echo "   - APK 将生成在: android/app/build/outputs/apk/debug/"
echo ""

echo "方案2: 安装完整开发环境"
echo "----------------------------------------"
echo "1. 安装 Java JDK:"
echo "   brew install openjdk@11"
echo ""
echo "2. 安装 Android Studio (包含 Android SDK):"
echo "   brew install --cask android-studio"
echo ""
echo "3. 配置环境变量 (添加到 ~/.zshrc):"
echo "   export ANDROID_HOME=\$HOME/Library/Android/sdk"
echo "   export PATH=\$PATH:\$ANDROID_HOME/emulator"
echo "   export PATH=\$PATH:\$ANDROID_HOME/tools"
echo "   export PATH=\$PATH:\$ANDROID_HOME/tools/bin"
echo "   export PATH=\$PATH:\$ANDROID_HOME/platform-tools"
echo ""
echo "4. 重新加载环境变量:"
echo "   source ~/.zshrc"
echo ""
echo "5. 构建 APK:"
echo "   cd android && ./gradlew assembleDebug"
echo ""

echo "方案3: 使用现有脚本 (需要先安装依赖)"
echo "----------------------------------------"
echo "1. 先完成方案2的环境配置"
echo "2. 运行构建脚本:"
echo "   ./build-apk.sh"
echo ""

echo "📋 文件说明:"
echo "- APK_BUILD_INSTRUCTIONS.md: 详细构建指南"
echo "- setup_build_env.sh: 环境检查脚本"
echo "- build-apk.sh: 自动构建脚本"
echo ""

echo "🎯 最快开始方式:"
echo "1. 下载 Android Studio: https://developer.android.com/studio"
echo "2. 安装完成后运行: npx cap open android"
echo "3. 在 Android Studio 中点击构建菜单"
echo ""
echo "预期结果: 生成 ~850MB 的完整游戏 APK 文件"
echo "========================================"